config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Web UI
  authenticate :user, lambda { |u| u.is_super_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Root
  root 'welcome#index'

  get  'timeline' => 'welcome#timeline'

  # Devise
  devise_for :users , controllers: {
    passwords:           "users/passwords",
    confirmations:       "users/confirmations",
    registrations:       "users/registrations",
    omniauth_callbacks:  "users/omniauth_callbacks"
  }
  # More Devise
  devise_scope :user do
    post "users/revoke_oauth" => "users/registrations#revoke_oauth"
  end

  # Resource
  resources :users,  only:   [:index, :update] do
    get "mention_query", on: :collection
  end
  resources :posts,  except: [:index]
  resources :topics, except: [:destroy]
  resources :messages
  resources :starred_topics, only: [:index, :destroy, :create]

  # Search
  post "search" => "search#search"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # Self joins
  has_many    :sub_topics,    class_name: 'Topic', foreign_key: 'parent_id', inverse_of: :parent_topic
  belongs_to  :parent_topic,  class_name: 'Topic', foreign_key: 'parent_id', inverse_of: :sub_topics

  # Has many Posts
  has_many    :posts, inverse_of: :topic

  # Has many relations with User
  has_many    :topic_users, inverse_of: :topic

  # Has many users
  has_many    :users, through: :topic_users

  # chattable
  has_many    :messages, inverse_of: :chattable, as: :chattable

  # has many events
  has_many    :events, inverse_of: :topic, dependent: :delete_all

  before_save do
    # update introduction_parsed and plain
    self.introduction_parsed = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true).render(self.introduction || "")
    self.introduction_plain  = Sanitize.clean(self.introduction_parsed, Sanitize::Config::STRICT)
    true
  end

  # Mount uploader
  mount_uploader :icon, IconUploader

  # Posts within this topic and subtopics
  def all_posts
    Post.where(topic_id: (self.all_sub_topic_ids_array | [ self.id ]), parent_id: 0)
  end

  def each_parent(with_self = false, &block)
    parent_history = []
    if with_self
      block.call(self) 
      parent_history << self.id
    end
    parent = self.parent_topic
    while parent.present? and !parent_history.include?(parent.id) do
      block.call(parent)
      parent_history << parent.id
      parent = parent.parent_topic
    end
  end

  def all_sub_topic_ids_array
    (self.all_sub_topic_ids || "").split(",").map { |id| id.to_i }
  end

  # Update all sub topic through recursive
  def update_all_sub_topic_ids
    ids = []
    Topic.find_all_sub_topic_ids self.id, ids
    self.all_sub_topic_ids = ids.compact.uniq.join(",")
    self.save
  end

  def update_all_parents_with_sub_topic_ids
    self.each_parent do |parent|
      parent.update_all_sub_topic_ids
    end
  end

  def self.find_all_sub_topic_ids(id, store)
    topic = Topic.find_by_id id
    if topic.present?
      ids = topic.sub_topic_ids - store
      store.concat(ids)
      ids.each do |sid|
        Topic.find_all_sub_topic_ids sid, store
      end
    end
  end

  # Posts count after a time
  def posts_count_unvisited(user)
    topic_user = TopicUser.find_by(user: user, topic: self)
    if topic_user.present? and topic_user.visited_at.present?
      self.all_posts.where("created_at > ?", topic_user.visited_at).count
    else
      self.all_posts.count
    end
  end

  # Mark User as Visited
  def mark_visited(user)
    TopicUser.find_or_create_by(topic: self, user: user).update(visited_at: Time.current)
  end

  # Helpers for stare
  def starring_users
    self.users.where("topic_users.is_starred" => true)
  end

  def all_starring_users
    users = []
    self.each_parent true do |topic|
      users |= topic.starring_users
    end
    users
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  if IslandZero.open_to_public
    before_action :authenticate_user!,  except: [:index, :show]
  else
    before_action :authenticate_user!
  end

  before_action :authenticate_admin!, only: [:edit, :update, :new, :create]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    params[:parent_id] = 0 unless params[:parent_id].present?
    @topics = Topic.where(params.permit(:parent_id)).order(:rank)
    respond_with(@topics)
  end

  def show
    # Setup message
    @chattable = @topic
    if user_signed_in?
      @new_message= Message.new(chattable: @topic)
    end

    # Reveal Objects
    @posts  = @topic.all_posts.order("id DESC").paginate(:page => params[:page])
    @sub_topics = @topic.sub_topics.order(:rank)

    # Form for tricks
    if user_signed_in?
      @new_post   = Post.new(topic: @topic)
    end

    # Update visited_at
    if user_signed_in?
      @topic.mark_visited current_user
    end

    # Render
    respond_with(@topic)
  end

  def new
    @topic = Topic.new(params.permit(:parent_id))
    respond_with(@topic)
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save

    # Update parent all_sub_topic_ids
    @topic.update_all_parents_with_sub_topic_ids

    respond_with(@topic)
  end

  def update
    old_parent = @topic.parent_topic

    @topic.update(topic_params)

    # Update parent all_sub_topic_ids
    @topic.update_all_parents_with_sub_topic_ids

    # Update old parent if necessary
    if old_parent.present? and old_parent.id != @topic.parent_id
      old_parent.update_all_sub_topic_ids
      old_parent.update_all_parents_with_sub_topic_ids
    end

    respond_with(@topic)
  end

  def destroy
    @topic.destroy

    # Update parent all_sub_topic_ids
    @topic.update_all_parents_with_sub_topic_ids

    respond_with(@topic)
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic)
      .permit(:title, :introduction, :parent_id, :rank, :icon)
      .clean_strict(:title)
      .clean_basic(:content)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
      <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:title) %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:icon) %>
    <%= image_tag @topic.icon_url, size: '64', class: 'thumbnail' %>
    <%= f.file_field :icon, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:parent_id) %><br>
    <%= f.text_field :parent_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:rank) %><br>
    <%= f.text_field :rank, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t(:introduction) %><br>
    <%= f.text_area :introduction, class: 'form-control', 'data-provide' => "markdown" %>
  </div>
  <div class="form-group text-center">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/topics/_index.html.erb
<div class="list-group">
<% topics.each do |topic| %>
  <%= link_to topic, class: 'list-group-item' do %>
    <h4 class="list-group-item-heading">
      <%= image_tag topic.icon_url, size: '32' %>
      &nbsp;
      <%= topic.title %> 
      <!--<small class="text-muted"><%= "##{topic.id}" %></small>-->
      <small class="text-muted pull-right text-right">
        <% if user_signed_in? %>
          <% count = topic.posts_count_unvisited current_user %>
          <% if count != 0 %>
            <span class="text-info">
              <%= t(:not_read_posts) %><%= count %>/
            </span>
          <% end %>
        <% end %>
        <%= t(:all_posts) %><%= topic.all_posts.count %>
      </small>
    </h4>
    <p class="list-group-item-text text-muted"><%= topic.introduction_plain.truncate(100) %></p>
  <% end %>
<% end %>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <div class="panel panel-primary panel-main">
        <div class="panel-body">
          <%= link_to t(:back), @topic %>
        </div>
        <div class="panel-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<% content_for :page_title, t(:all_topics) %>

<div class="container">
  <div class="row">

    <div class="col-md-8">

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default panel-main">

            <div class="panel-body">
              <span>
                <%= glyphicon 'list' %>
                <%= t(:all_topics) %>
              </span>
              <% if user_signed_in? %>
                <% if current_user.is_admin %>
                  <span class="pull-right">
                    <%= link_to t(:new_topic), new_topic_path %>
                  </span>
                <% else %>
                  <span class="pull-right">
                    <%= link_to t(:suggest_new_topic), topic_path(ENV['IZ_TOPIC_SUGGEST']) %>
                  </span>
                <% end %>
              <% end %>
            </div>

            <%= render 'index', topics: @topics %>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <div class="panel panel-primary panel-main">

        <div class="panel-body">
          <% if @topic.parent_id == 0 %>
          <%= link_to 'Back', topics_path %>
          <% else %>
          <%= link_to 'Back', topic_path(@topic.parent_id) %>
          <% end %>
        </div>

        <div class="panel-body text-center">
          <h3><%= t(:new_topic) %></h3>
        </div>

        <div class="panel-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<% content_for :page_title, @topic.title %>

<div class="container">
  <div class="row">

    <div class="col-md-8">

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-primary panel-main">
            <div class="panel-heading">
              <% if @topic.parent_id == 0 %>
                <%= link_to topics_path, class: 'text-white' do %>
                  <%= glyphicon 'chevron-left' %><%= t(:back_to_all_topics) %>
                <% end %>
              <% else %>
                <% if @topic.parent_topic.present? %>
                  <%= link_to topic_path(@topic.parent_topic), class: 'text-white' do %>
                    <%= glyphicon 'chevron-left' %><%= "#{t(:back_to_parent_topic)}: #{@topic.parent_topic.title}" %>
                  <% end %>
                <% end %>
              <% end %>

              <% if user_signed_in? %>
                <% if @topic.starring_users.include? current_user %>
                  <%= link_to t(:unstar), starred_topic_path(@topic.id), method: :delete, remote: true, class: 'text-white pull-right need-reload' %>
                <% else %>
                  <%= link_to t(:star), starred_topics_path(id: @topic.id), method: :post, remote: true, class: 'text-white pull-right need-reload' %>
                <% end %>
              <% end %>
            </div>
            <div class="panel-body">
              <h3>
                <%= image_tag @topic.icon_url , size: '64' %>
                &nbsp;
                <!--<small class="text-muted">#<%= @topic.id %></small>--> 
                <%= @topic.title %>
              </h3>
              <br/>
              <%= @topic.introduction_parsed.html_safe %>

              <% if user_signed_in? and current_user.is_admin %>
                <div class="text-right">
                  <p>
                  <%= link_to t(:edit), edit_topic_path(@topic) %> |
                  <%= link_to t(:new_sub_topic), new_topic_path(parent_id: @topic.id) %>
                  </p>
                </div>
              <% end %>
            </div>
            <%= render 'index', topics: @sub_topics %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">

            <% if @new_post.present? %>
              <div class="panel-body text-right">
                <a id="linkNewPost" data-toggle="collapse" href="#collapseNewPost" aria-expanded="true" aria-controls="collapseNewPost">
                  <%= glyphicon 'pencil' %><%= t(:new_post) %>
                </a>
              </div>

              <div id="collapseNewPost" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                  <%= form_for @new_post, remote: true do |f| %>
                    <%= f.hidden_field :topic_id %>
                    <div class="form-group">
                      <%= f.text_field :title, class: 'form-control', id: 'newPostInputTitle', placeholder: t("title") %>
                    </div>
                    <div class="form-group">
                      <%= f.text_area :content, class: 'form-control with-at-support', id: 'newPostInputContent', placeholder: t("content"), 'data-provide' => "markdown" %>
                    </div>
                    <div class="form-group text-right">
                      <%= f.submit t("submit"), class: "btn btn-sm btn-default", id: 'newPostSubmit' %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% else %>
              <% if !user_signed_in? %>
                <div class="panel-body text-center text-muted">
                  <%= t(:login_to_create_post) %>
                </div>
              <% end %>
            <% end %>

            <% if @posts.total_pages > 1 %>
              <hr class="clean" />
              <div class="panel-body">
                <%= will_paginate @posts %>
              </div>
            <% end %>

            <div class="list-group">
              <% if @posts.length != 0 %>

                <% @posts.each do |post| %>
                  <%= link_to post, class: 'list-group-item' do %>
                    <h4 class="list-group-item-heading">
                      <span>
                        <%= post.title %>
                      </span>
                      <% if post.topic != @topic %>
                        <span class="label label-default pull-right"><%= post.topic.title %></span>
                      <% end %>
                      <br/>
                      <small class="text-primary">
                        <%= post.user.nickname %> |
                        <%= time_ago_in_words post.created_at %>
                      </small>
                    </h4>
                    <p class="list-group-item-text text-muted">
                    <%= post.content_plain.truncate(100) %>
                    </p>
                  <% end %>
                <% end %>

              <% else %>

                <li class="list-group-item text-center"><%= t(:no_posts) %></li>

              <% end %>
            </div>

            <% if @posts.total_pages > 1 %>
              <div class="panel-body">
                <%= will_paginate @posts %>
              </div>
            <% end %>

            <% if @new_post.present? and @posts.length > 5 %>
              <% if @posts.total_pages > 1 %>
                <hr class="clean" />
              <% end %>
              <div class="panel-body text-right">
                <a id="alt-new-post" href="#">
                  <%= glyphicon 'pencil' %><%= t(:new_post) %>
                </a>
              </div>
            <% end %>

          </div>
        </div>
      </div>

    </div>

    <div class="col-md-4">
      <%= render 'shared/chatbox' %>
    </div>

  </div>
</div>