config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Web UI
  authenticate :user, lambda { |u| u.is_super_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Root
  root 'welcome#index'

  get  'timeline' => 'welcome#timeline'

  # Devise
  devise_for :users , controllers: {
    passwords:           "users/passwords",
    confirmations:       "users/confirmations",
    registrations:       "users/registrations",
    omniauth_callbacks:  "users/omniauth_callbacks"
  }
  # More Devise
  devise_scope :user do
    post "users/revoke_oauth" => "users/registrations#revoke_oauth"
  end

  # Resource
  resources :users,  only:   [:index, :update] do
    get "mention_query", on: :collection
  end
  resources :posts,  except: [:index]
  resources :topics, except: [:destroy]
  resources :messages
  resources :starred_topics, only: [:index, :destroy, :create]

  # Search
  post "search" => "search#search"

end

app/views/shared/_chatbox.html.erb
<% if @chattable.present? %>
  <% messages = @chattable.messages.order("id DESC").first(50) %>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-success panel-main">
        <div class="panel-heading">
          Chatbox
        </div>
        <% if @new_message.present? %>
          <div class="panel-body">
            <%= form_for @new_message, remote: true, html: { id: 'chatroom-send-form' } do |f| %>
              <%= f.hidden_field :chattable_type %>
              <%= f.hidden_field :chattable_id %>
              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <%= f.text_field :content, class: 'form-control', id: 'input-content' %>
                  </div>
                </div>
                <div class="col-md-2">
                  <%= f.submit t(:send), class: 'btn btn-default' %>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <% if !user_signed_in? %>
            <div class="panel-body text-center text-muted">
              <%= t(:login_to_chat) %>
            </div>
          <% end %>
        <% end %>
        <div class="panel-body" id="chatroom-content">
          <% messages.each do |msg| %>
            <%= render partial: 'shared/chatitem', locals: { msg: msg } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_chatitem.html.erb
<p class="text-primary">
  <small class="text-muted">
    <%= msg.user.nickname %> (#<%= msg.user.id %>)
    <span class="pull-right"><%= time_ago_in_words msg.created_at %></span>
  </small>
  <br/>
  <%= msg.content %>
</p>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <p>
      <small>Copyright 2015 IslandZero</small>&nbsp;<small><a href="mailto:hi@island0.com">hi@island0.com</a></small>
      <br/>
      <small>Powered By <%= link_to 'Ruby on Rails', 'http://rubyonrails.org' %> | Themed By <%= link_to 'Bootswatch', 'http://bootswatch.com' %></small>
      <br/>
      <small>Links: <%= link_to "Github Repo", 'https://github.com/IslandZero/IslandZero.git' %> | <%= link_to "YANKE.IO", 'http://yanke.io' %> | <%= link_to 'Donate', 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KTR8BN7CF9CZ4' %></small>
    </p>
    <br/>
  </div>
</div>

app/views/shared/_ga.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', '<%= ENV['GA_TRACK_ID'] %>', 'auto');
ga('send', 'pageview');

</script>
<% end %>

app/views/shared/_ga_head.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', '<%= ENV['GA_TRACK_ID'] %>', 'auto');

</script>
<% end %>

app/views/shared/_ga_page_view.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>ga('send', 'pageview');</script>
<% end %>

app/views/shared/_nav.erb
<div class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "iz_logo_white.png", height: '26' %>
    <% end %>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <% if user_signed_in? or IslandZero.open_to_public %>
      <%= form_tag search_path, class: "navbar-form navbar-left", role: "search" do %>
        <div class="form-group">
          <%= text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: t(:search_topic) %>
        </div>
        <button type="submit" class="btn btn-info"><%= glyphicon :search %></button>
      <% end %>
    <% end %>
    <ul class="nav navbar-nav navbar-left">
      <% if user_signed_in? %>
        <%= li_link nil, timeline_path do %>
          <%= glyphicon 'inbox' %>
          <%= t('activites') %>&nbsp;<span id="events-badge" class="badge"></span>
        <% end %>
      <% end %>
      <% if user_signed_in? or IslandZero.open_to_public %>
        <%= li_link nil, topics_path do %>
          <%= glyphicon 'list' %>
          <%= t('all_topics') %>
        <% end %>
      <% end %>
      <% if user_signed_in? %>
        <%= li_link nil, starred_topics_path do %>
          <%= glyphicon 'star' %>
          <%= t('starred_topics') %>
        <% end %>
      <% end %>
      <% if user_signed_in? and current_user.is_super_admin %>
        <%= li_link nil, users_path do %>
          <%= glyphicon 'user' %>
          <%= t('all_users') %>
        <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= glyphicon :user %>&nbsp<%= current_user.nickname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <%= glyphicon :home %>
                <%= t(:profile) %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, { method: :delete } do %>
                <%= glyphicon :off %>
                <%= t(:logout) %>
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <%= li_link nil, new_user_session_path do %>
          <%= glyphicon 'log-in' %>
          <%= t('login') %>
        <% end %>
        <%= li_link nil, new_user_registration_path do %>
          <%= glyphicon 'pencil' %>
          <%= t('register') %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
</div>