config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Web UI
  authenticate :user, lambda { |u| u.is_super_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Root
  root 'welcome#index'

  get  'timeline' => 'welcome#timeline'

  # Devise
  devise_for :users , controllers: {
    passwords:           "users/passwords",
    confirmations:       "users/confirmations",
    registrations:       "users/registrations",
    omniauth_callbacks:  "users/omniauth_callbacks"
  }
  # More Devise
  devise_scope :user do
    post "users/revoke_oauth" => "users/registrations#revoke_oauth"
  end

  # Resource
  resources :users,  only:   [:index, :update] do
    get "mention_query", on: :collection
  end
  resources :posts,  except: [:index]
  resources :topics, except: [:destroy]
  resources :messages
  resources :starred_topics, only: [:index, :destroy, :create]

  # Search
  post "search" => "search#search"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:timeline]

  def index
    if user_signed_in?
      if current_user.events.count == 0
        redirect_to topics_path
      else
        redirect_to timeline_path
      end
    else
      if IslandZero.open_to_public
        redirect_to topics_path
      end
    end
  end

  def timeline
    @events = current_user.events.order("id DESC").paginate(page: params[:page])
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def user_or_me(user)
    return "" if user.nil?
    if user.id == current_user.id
      t(:you)
    else
      "#{user.nickname}(#{user.id})"
    end
  end

end

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>IslandZero</h1>
    <p><%= t(:islandzero_introduction) %></p>
    <% unless user_signed_in? %>
    <p>
      <%= link_to t(:login), new_user_session_path, class: 'btn btn-primary' %>
      <%= link_to t(:register), new_user_registration_path, class: 'btn btn-success' %>
    </p>
    <% end %>
  </div>
</div>

app/views/welcome/timeline.html.erb
<div class="container">
<div class="row">
  <div class="col-md-8">

    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default panel-main">

          <div class="panel-body">
            <%= glyphicon 'inbox' %>
            <%= t :activites %>
          </div>

          <% if @events.total_pages > 1 %>
            <hr class="clean" />
            <div class="panel-body">
              <%= will_paginate @events %>
            </div>
          <% end %>

          <ul class="list-group">
            <% if @events.count == 0 %>
              <li class="list-group-item text-center"><%= t(:no_activities) %></li>
            <% else %>
              <% @events.each do |event| %>
                <li class="list-group-item">
                  <% if event.topic.present? %>
                    <%= image_tag event.topic.icon_url, size: '32' %>
                  <% end %>

                  <span class="text-muted text-right pull-right">
                    <small><%= time_ago_in_words event.created_at %></small>
                  </span>

                  <% if event.topic.present? %>
                    <span class="text-muted">
                      <small>
                        <%= t(:from_topic) %> 
                        <%= link_to event.topic.title, topic_path(event.topic) %>
                      </small>
                    </span>
                    <br/>
                  <% end %>

                  <% if event.event_type == Event::Type::Mention %>
                    <% if event.post.present? and event.sub_post.present? %>
                      <span class="<%= "text-info" if event.post.user_id == current_user.id %>">
                        <small>
                          <% if event.post.user_id == current_user.id %>
                            <%= t(:from_your_post) %>
                          <% else %>
                            <%= t(:from_post) %>
                          <% end %>
                          "
                          <%= link_to event.post.title, post_path(event.post) %>
                          "
                        </small>
                        <br/>
                      </span>

                      <small>
                        <%= t(:from_reply) %>
                        "
                        <%= link_to truncate(event.sub_post.content_plain, length: 50), post_path(event.post, jump_sub_post: event.sub_post.id) %>"
                      </small>
                        </br>
                        <strong>
                          <%= user_or_me event.sub_post.user %>
                          <%= t(:mentioned_you) %>
                        </strong>
                        .
                      <% else %>
                        <% if event.post.present? %>
                          <span class="<%= "text-info" if event.post.user_id == current_user.id %>">
                            <small>
                              <% if event.post.user_id == current_user.id %>
                                <%= t(:from_your_post) %>
                              <% else %>
                                <%= t(:from_post) %>
                              <% end %>
                              "
                              <%= link_to event.post.title, post_path(event.post) %>
                              "
                            </small>
                            <br/>
                          </span>
                        <% end %>
                        <strong>
                          <%= user_or_me event.post.user %>
                          <%= t(:mentioned_you) %>
                        </strong>
                      <% end %>
                    <% end %>

                    <% if event.event_type == Event::Type::NewPost and event.post.present? %>
                      <strong>
                        <%= user_or_me event.post.user %> 
                        <%= t(:create_a_post) %> 
                        "
                        <%= link_to event.post.title, post_path(event.post) %>
                        "
                        .
                      </strong>
                    <% end %>

                    <% if event.event_type == Event::Type::NewSubPost and event.post.present? and event.sub_post.present? %>
                      <span class="<%= "text-info" if event.post.user_id == current_user.id %>">
                        <small>
                          <% if event.post.user_id == current_user.id %>
                            <%= t(:from_your_post) %>
                          <% else %>
                            <%= t(:from_post) %>
                          <% end %>
                          "
                          <%= link_to event.post.title, post_path(event.post) %>
                          "
                        </small>
                        <br/>
                      </span>

                      <% if event.count == 1 %>

                        <strong>
                          <%= user_or_me event.sub_post.user %> 
                          <%= t(:create_a_sub_post) %>
                          "
                          <%= link_to truncate(event.sub_post.content_plain, length: 50), post_path(event.post, jump_sub_post: event.sub_post.id) %>
                          "
                          .
                        </strong>

                      <% else %>

                        <strong>
                          <%= t('multiple_sub_posts_created', count: event.count) %>
                          .
                        </strong>

                      <% end %>
                    <% end %>

                </li>
              <% end %>
            <% end %>
          </ul>

          <% if @events.total_pages > 1 %>
            <hr class="clean" />
            <div class="panel-body">
              <%= will_paginate @events %>
            </div>
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>
</div>

<meta name="timeline-page" content="true">